apiVersion: v1
kind: Service
metadata:
  namespace: tgbot
  name: tghomebot
spec:
  selector:
    app: tghomebot
  ports:
    - protocol: TCP
      port: 12001
      targetPort: 12001
      name: http
  type: ClusterIP
